# Generated by Django 4.0.3 on 2022-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes_verification', '0002_alter_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
